#!/usr/bin/env node

import { execSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = process.cwd()
const ENV_PATH = resolve(ROOT, '.env.local')

function run(command, options = {}) {
  return execSync(command, {
    cwd: ROOT,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf8',
    ...options,
  })
}

function runInherit(command) {
  execSync(command, {
    cwd: ROOT,
    stdio: 'inherit',
    encoding: 'utf8',
  })
}

function fail(message) {
  console.error(`\n[bootstrap-demo] ${message}`)
  process.exit(1)
}

function commandExists(command) {
  try {
    run(`command -v ${command}`)
    return true
  } catch {
    return false
  }
}

function parseEnvText(text) {
  const vars = {}
  const lines = text.split(/\r?\n/)
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const clean = trimmed.startsWith('export ') ? trimmed.slice(7) : trimmed
    const eqIndex = clean.indexOf('=')
    if (eqIndex === -1) continue
    const key = clean.slice(0, eqIndex).trim()
    let value = clean.slice(eqIndex + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    vars[key] = value
  }
  return vars
}

function getExistingEnvVars() {
  if (!existsSync(ENV_PATH)) return {}
  return parseEnvText(readFileSync(ENV_PATH, 'utf8'))
}

function ensureNodeVersion() {
  const major = Number.parseInt(process.versions.node.split('.')[0], 10)
  if (Number.isNaN(major) || major < 22) {
    fail(
      `Node.js 22+ é obrigatório. Versão atual: ${process.versions.node}. Use \`nvm use\` (arquivo .nvmrc).`
    )
  }
}

function ensureTooling() {
  if (!commandExists('docker')) {
    fail('Docker não encontrado. Instale o Docker Desktop e tente novamente.')
  }

  if (!commandExists('supabase')) {
    fail('Supabase CLI não encontrado. Instale com `brew install supabase/tap/supabase`.')
  }

  try {
    run('docker info')
  } catch {
    fail('Docker não está em execução. Abra o Docker Desktop e tente novamente.')
  }
}

function ensureDependencies() {
  if (existsSync(resolve(ROOT, 'node_modules'))) {
    console.log('[bootstrap-demo] node_modules já existe. Pulando npm install.')
    return
  }

  console.log('[bootstrap-demo] Instalando dependências (npm install)...')
  runInherit('npm install')
}

function startAndResetSupabase() {
  console.log('[bootstrap-demo] Iniciando stack local do Supabase...')
  runInherit('supabase start')

  console.log('[bootstrap-demo] Aplicando migrations + seed demo (supabase db reset --local --yes)...')
  runInherit('supabase db reset --local --yes')
}

function getSupabaseStatusEnv() {
  try {
    const output = run('supabase status -o env')
    return parseEnvText(output)
  } catch (error) {
    fail('Não foi possível obter credenciais locais via `supabase status -o env`.')
  }
}

function buildEnvFile(existingVars, supabaseVars) {
  const supabaseUrl =
    supabaseVars.NEXT_PUBLIC_SUPABASE_URL ||
    supabaseVars.SUPABASE_URL ||
    supabaseVars.API_URL ||
    'http://127.0.0.1:54321'

  const anonKey =
    supabaseVars.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
    supabaseVars.SUPABASE_ANON_KEY ||
    supabaseVars.ANON_KEY ||
    ''

  const serviceRoleKey =
    supabaseVars.SUPABASE_SERVICE_ROLE_KEY ||
    supabaseVars.SERVICE_ROLE_KEY ||
    ''

  if (!anonKey || !serviceRoleKey) {
    fail('Não foi possível detectar ANON_KEY e SERVICE_ROLE_KEY do Supabase local.')
  }

  const siteUrl = existingVars.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
  const googleMapsApiKey = existingVars.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || ''

  return [
    '# -----------------------------------------------------------------------------',
    '# Auto-generated by scripts/bootstrap-demo.mjs',
    '# -----------------------------------------------------------------------------',
    'NEXT_PUBLIC_SUPABASE_URL=' + supabaseUrl,
    'NEXT_PUBLIC_SUPABASE_ANON_KEY=' + anonKey,
    'SUPABASE_SERVICE_ROLE_KEY=' + serviceRoleKey,
    'NEXT_PUBLIC_SITE_URL=' + siteUrl,
    '',
    '# Opcional: habilita autocomplete/mapas do Google',
    'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=' + googleMapsApiKey,
    '',
  ].join('\n')
}

function writeEnvFile(contents) {
  writeFileSync(ENV_PATH, contents, 'utf8')
  console.log(`[bootstrap-demo] Arquivo .env.local atualizado em ${ENV_PATH}`)
}

function main() {
  console.log('[bootstrap-demo] Validando pré-requisitos...')
  ensureNodeVersion()
  ensureTooling()

  ensureDependencies()
  startAndResetSupabase()

  const existingVars = getExistingEnvVars()
  const supabaseVars = getSupabaseStatusEnv()
  const envContents = buildEnvFile(existingVars, supabaseVars)
  writeEnvFile(envContents)

  console.log('[bootstrap-demo] Setup concluído. Use `npm run dev:demo` para iniciar a aplicação.')
}

main()
